# Generated by Django 5.2.8 on 2025-11-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do continente')),
            ],
            options={
                'verbose_name': 'Continente',
                'verbose_name_plural': 'Continentes',
            },
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
                ('insta', models.CharField(max_length=100, verbose_name='Instagram')),
                ('face', models.CharField(max_length=100, verbose_name='Facebook')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name': 'Elenco',
                'verbose_name_plural': 'Elencos',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do episódio')),
            ],
            options={
                'verbose_name': 'Episódio',
                'verbose_name_plural': 'Episódios',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField(verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do filme')),
                ('duracao', models.IntegerField(verbose_name='Duração do filme')),
                ('sinopse', models.CharField(max_length=1000, verbose_name='Sinopse')),
                ('site_oficial', models.CharField(max_length=100, verbose_name='Site do filme')),
                ('data_lancamento', models.DateField(verbose_name='Data de lançamento')),
                ('nota_avaliacao', models.FloatField(verbose_name='Nota da avaliação')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.elenco', verbose_name='Elenco')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.elenco', verbose_name='Ator')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filme', verbose_name='Filme')),
            ],
            options={
                'verbose_name': 'Atuação',
                'verbose_name_plural': 'Atuações',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do país')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.continente', verbose_name='Continente')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='País'),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da série')),
                ('temporadas', models.IntegerField(verbose_name='Temporadas da série')),
                ('sinopse', models.CharField(max_length=1000, verbose_name='Sinopse')),
                ('site_oficial', models.CharField(max_length=100, verbose_name='Site da série')),
                ('data_lancamento', models.DateField(verbose_name='Data de lançamento')),
                ('nota_avaliacao', models.FloatField(verbose_name='Nota da avaliação')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.elenco', verbose_name='Elenco')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='EpisodiosSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.IntegerField(verbose_name='Duração')),
                ('data_disponibilizacao', models.DateField(verbose_name='Data de disponibilização')),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.episodio', verbose_name='Episódio da série')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serie', verbose_name='Nome da série')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temporada', verbose_name='Temporada da série')),
            ],
            options={
                'verbose_name': 'Episódio da série',
                'verbose_name_plural': 'Episódios da série',
            },
        ),
    ]
