# Generated by Django 5.2.8 on 2025-12-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodiosserie',
            options={'verbose_name': 'Episódio de série', 'verbose_name_plural': 'Episódios de série'},
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.elenco', verbose_name='Diretor'),
        ),
    ]
