# Generated by Django 5.2.9 on 2025-12-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_episodiosserie_options_alter_filme_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='serie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.serie', verbose_name='Série'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EpisodiosSerie',
        ),
    ]
