# Generated by Django 5.2.9 on 2025-12-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_episodio_serie_id_delete_episodiosserie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodio',
            old_name='serie_id',
            new_name='serie',
        ),
    ]
