# Generated by Django 5.2.9 on 2025-12-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_serie_id_episodio_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.AddField(
            model_name='elenco',
            name='filme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.filme', verbose_name='Filme'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Atuacao',
        ),
    ]
