# Generated by Django 5.2.9 on 2025-12-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_filme_diretor_elenco_filme_delete_atuacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elenco',
            new_name='Ator',
        ),
        migrations.AlterModelOptions(
            name='ator',
            options={'verbose_name': 'Ator', 'verbose_name_plural': 'Atores'},
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
                ('insta', models.CharField(max_length=100, verbose_name='Instagram')),
                ('face', models.CharField(max_length=100, verbose_name='Facebook')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filme', verbose_name='Filme')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.AlterField(
            model_name='serie',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor', verbose_name='Elenco'),
        ),
    ]
