# Generated by Django 5.2.9 on 2025-12-15 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_elenco_ator_alter_ator_options_diretor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diretor',
            name='filme',
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.diretor', verbose_name='Diretor'),
            preserve_default=False,
        ),
    ]
